export const filterData = [
  {name: 'Fast food', image: require('../assets/fastfood.png'), id: '0'},
  {name: 'Burgers', image: require('../assets/burger.png'), id: '1'},
  {name: 'Salads', image: require('../assets/salads.png'), id: '2'},
  {name: 'Chinese', image: require('../assets/chinese.png'), id: '3'},
  {name: 'Maxican', image: require('../assets/maxican.png'), id: '4'},
  {name: 'Sea food', image: require('../assets/seafood.png'), id: '5'},
  {name: 'Hotdog', image: require('../assets/hotdog.png'), id: '6'},
  {name: 'Fast food', image: require('../assets/fastfood.png'), id: '8'},
  {name: 'Burgers', image: require('../assets/burger.png'), id: '9'},
  {name: 'Salads', image: require('../assets/salads.png'), id: '10'},
  {name: 'Chinese', image: require('../assets/chinese.png'), id: '11'},
  {name: 'Maxican', image: require('../assets/maxican.png'), id: '12'},
  {name: 'Sea food', image: require('../assets/seafood.png'), id: '13'},
  {name: 'Hotdog', image: require('../assets/hotdog.png'), id: '14'},
];

export const foodCardData = [
  {
    restaurantName: 'Mc Donalds',
    farAway: '21.2',
    businessAddress: '22 Bessie street, Cape Town',
    images:
      'https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.9,
    numberOfReview: 274352,
    coordinates: {lat: -26.1888612, lng: 28.246325},
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: 'Burgers, wraps,Milkshakes...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image:
          'https://images.pexels.com/photos/1581384/pexels-photo-1581384.jpeg?auto=compress&cs=tinysrgb&w=600',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 0,
  },
  {
    restaurantName: 'KFC',
    farAway: '12.7',
    businessAddress: '22 Bessie street, Cape Town',
    images:
      'https://images.pexels.com/photos/1581384/pexels-photo-1581384.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.3,
    numberOfReview: 3406,
    coordinates: {lat: -26.1891648, Ing: 28.2441808},
    discount: 20,
    deliveryTime: 30,
    collectTime: 10,
    foodType: 'Chicken, Chicken wings...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 1,
  },
  {
    restaurantName: 'Steers',
    farAway: '5',
    businessAddress: ' 17 0livia Rd, Johannesburg',
    images:
      'https://images.pexels.com/photos/1267315/pexels-photo-1267315.jpeg?auto=compress&cs=tinysrgb&w=600',
    coordinates: {lat: -26.1886781, Ing: 28.244879},
    averageReview: 4.9,
    numberOfReview: 1272,
    discount: 12,
    deliveryTime: 25,
    collectTime: 15,
    foodType: 'Flame grilled beef Burgers',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 2,
  },
  {
    restaurantName: 'Roman Pizza',
    farAway: '7',
    businessAddress: ' 15 Atlas Rd, Kempton Park',
    images:
      'https://images.pexels.com/photos/1855214/pexels-photo-1855214.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.3,
    numberOfReview: 7050,
    coordinates: {lat: -26.1845336, Ing: 28.2481691},
    discount: 5,
    deliveryTime: 20,
    collectTime: 10,
    foodType: 'Chicken pizza, Vegetarian pizza...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 3,
  },
  {
    restaurantName: 'Roman Pizza',
    farAway: '7',
    businessAddress: ' 15 Atlas Rd, Kempton Park',
    images:
      'https://images.pexels.com/photos/9482636/pexels-photo-9482636.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.3,
    numberOfReview: 700,
    coordinates: {lat: -26.1845336, Ing: 28.2481691},
    discount: 5,
    deliveryTime: 20,
    collectTime: 10,
    foodType: 'Chicken pizza, Vegetarian pizza...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 4,
  },
  {
    restaurantName: 'Roman Pizza',
    farAway: '7',
    businessAddress: ' 15 Atlas Rd, Kempton Park',
    images:
      'https://images.pexels.com/photos/14680058/pexels-photo-14680058.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.3,
    numberOfReview: 700,
    coordinates: {lat: -26.1845336, Ing: 28.2481691},
    discount: 5,
    deliveryTime: 20,
    collectTime: 10,
    foodType: 'Chicken pizza, Vegetarian pizza...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 5,
  },
  {
    restaurantName: 'Roman Pizza',
    farAway: '7',
    businessAddress: ' 15 Atlas Rd, Kempton Park',
    images:
      'https://images.pexels.com/photos/2696064/pexels-photo-2696064.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.3,
    numberOfReview: 700,
    coordinates: {lat: -26.1845336, Ing: 28.2481691},
    discount: 5,
    deliveryTime: 50,
    collectTime: 10,
    foodType: 'Chicken pizza, Vegetarian pizza...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 6,
  },
  {
    restaurantName: 'KFC',
    farAway: '12.7',
    businessAddress: '22 Bessie street, Cape Town',
    images:
      'https://images.pexels.com/photos/1581384/pexels-photo-1581384.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.3,
    numberOfReview: 3406,
    coordinates: {lat: -26.1891648, Ing: 28.2441808},
    discount: 20,
    deliveryTime: 30,
    collectTime: 10,
    foodType: 'Chicken, Chicken wings...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 7,
  },
  {
    restaurantName: 'Steers',
    farAway: '5',
    businessAddress: ' 17 0livia Rd, Johannesburg',
    images:
      'https://images.pexels.com/photos/1267315/pexels-photo-1267315.jpeg?auto=compress&cs=tinysrgb&w=600',
    coordinates: {lat: -26.1886781, Ing: 28.244879},
    averageReview: 4.9,
    numberOfReview: 1272,
    discount: 12,
    deliveryTime: 25,
    collectTime: 15,
    foodType: 'Flame grilled beef Burgers',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 8,
  },
  {
    restaurantName: 'Roman Pizza',
    farAway: '7',
    businessAddress: ' 15 Atlas Rd, Kempton Park',
    images:
      'https://images.pexels.com/photos/1855214/pexels-photo-1855214.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.3,
    numberOfReview: 7050,
    coordinates: {lat: -26.1845336, Ing: 28.2481691},
    discount: 5,
    deliveryTime: 20,
    collectTime: 10,
    foodType: 'Chicken pizza, Vegetarian pizza...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 9,
  },
  {
    restaurantName: 'Roman Pizza',
    farAway: '7',
    businessAddress: ' 15 Atlas Rd, Kempton Park',
    images:
      'https://images.pexels.com/photos/9482636/pexels-photo-9482636.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.3,
    numberOfReview: 700,
    coordinates: {lat: -26.1845336, Ing: 28.2481691},
    discount: 5,
    deliveryTime: 20,
    collectTime: 10,
    foodType: 'Chicken pizza, Vegetarian pizza...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 10,
  },
  {
    restaurantName: 'Roman Pizza',
    farAway: '7',
    businessAddress: ' 15 Atlas Rd, Kempton Park',
    images:
      'https://images.pexels.com/photos/14680058/pexels-photo-14680058.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.3,
    numberOfReview: 700,
    coordinates: {lat: -26.1845336, Ing: 28.2481691},
    discount: 5,
    deliveryTime: 20,
    collectTime: 10,
    foodType: 'Chicken pizza, Vegetarian pizza...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 11,
  },
  {
    restaurantName: 'Roman Pizza',
    farAway: '7',
    businessAddress: ' 15 Atlas Rd, Kempton Park',
    images:
      'https://images.pexels.com/photos/2696064/pexels-photo-2696064.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.3,
    numberOfReview: 700,
    coordinates: {lat: -26.1845336, Ing: 28.2481691},
    discount: 5,
    deliveryTime: 50,
    collectTime: 10,
    foodType: 'Chicken pizza, Vegetarian pizza...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 12,
  },
  {
    restaurantName: 'Mc Donalds',
    farAway: '21.2',
    businessAddress: '22 Bessie street, Cape Town',
    images:
      'https://images.pexels.com/photos/260922/pexels-photo-260922.jpeg?auto=compress&cs=tinysrgb&w=600',
    averageReview: 4.9,
    numberOfReview: 274352,
    coordinates: {lat: -26.1888612, lng: 28.246325},
    discount: 10,
    deliveryTime: 15,
    collectTime: 5,
    foodType: 'Burgers, wraps,Milkshakes...',
    productData: [
      {
        name: 'Hand cut chips',
        price: 29.3,
        image:
          'https://images.pexels.com/photos/1581384/pexels-photo-1581384.jpeg?auto=compress&cs=tinysrgb&w=600',
      },
      {
        name: 'Big Mac',
        price: 50.8,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png',
      },
      {
        name: 'Chicken Burger',
        price: 70,
        image: 'https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png',
      },
    ],
    id: 13,
  },
];
